### PR TITLE
refactor: use add_downloaded_id

### PR DESCRIPTION
**Pull request by momoandbanana22**

### CODE REVIEW

**Comment by hare1039** [comment]
@momoandbanana22 
Thanks!
BTW, I can add you to the collaborators for this repo if you like, so you can directly push commits here.

**Comment by momoandbanana22** [comment]
@hare1039  wow, thank you ! so, please add me to collaborator. (^_^)

**Comment by hare1039** [comment]
I've added you to the collaborator. Feel free to commit anytime.
It's a small project, so no pressure of being a collaborator (✿´꒳`)ﾉ°+.

**Comment by momoandbanana22** [comment]
thank you for added ! 🥰

**Pull request merged**
